default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost


development:
  <<: *default
  database: todo_development #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

test:
  <<: *default
  database: todo_test #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

production:
  <<: *default
  database: todo_production
  username: sample_app
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
