default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost


development:
  <<: *default
  database: todo_development #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

test:
  <<: *default
  database: todo_test #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

production:
  <<: *default
  database: todo_app_production
  username: root
  password: <%= ENV['TODO_APP_DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
